name = "presensi-api"
main = "src/index.js"
compatibility_date = "2025-12-11"

# Kalau pakai routes, bisa tambahkan:
# routes = [
#   { pattern = "presensi-api.wawan.workers.dev/*", zone_name = "" }
# ]

[[d1_databases]]
binding = "DB"
database_name = "presensi"
database_id = "57391686-9de8-4102-88c8-8ca539e4efa1"
